Repository pagopa/pagopa-api-config-selfcare-integration, pull requests merged in 2023-12, with the labels that each got.

#22 fix: Helm
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small

#23 update starter 1.17.0
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/mapper/ConvertCanaliToChannelDetails.java
Labels: size/small

#24 fix: added GH action secret as TF resource
  .identity/00_data.tf
  .identity/03_github_environment.tf
Labels: size/small, ignore-for-release

#26 [PASELC-658] API for get a list of IBAN by creditor institution batch
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/config/MappingsConfiguration.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/controller/IbanController.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/mapper/ConvertIbanMasterToIbanDetail.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/model/PageInfo.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/model/iban/IbanDetails.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/model/iban/IbanLabel.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/model/iban/IbansList.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/repository/ExtendedIbanMasterRepository.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/service/IbansService.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/util/Constants.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/util/Utility.java
  src/main/resources/h2/data-h2.sql
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/controller/IbanControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/service/IbanServiceTest.java
  src/test/java/it/gov/pagopa/apiconfig/util/TestUtil.java
  src/test/resources/response/get_broker_channels_details_ok1.json
  src/test/resources/response/get_broker_stations_details_ok1.json
  src/test/resources/response/get_creditorinstitution_stations_details_ok1.json
  src/test/resources/response/get_ibans_ok1.json
  src/test/resources/response/get_ibans_ok2.json
Labels: enhancement, size/large
