Repository pagopa/pagopa-api-config-selfcare-integration, pull requests merged in 2024-05, with the labels that each got.

#45 switch url backend
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/policy/_base_policy.xml
  openapi/openapi.json
  pom.xml
Labels: size/small, skip, on hold

#46 [VAS-912] fix: Retrieve segregation code API
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/config/OpenApiConfig.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/controller/CreditorInstitutionController.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/model/code/AvailableCodes.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/repository/ExtendedCreditorInstitutionStationRepository.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/service/CreditorInstitutionsService.java
  src/main/resources/application-h2.properties
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/apiconfig/selfcareintegration/controller/CreditorInstitutionsControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/selfcareintegration/service/CreditorInstitutionsServiceTest.java
  src/test/java/it/gov/pagopa/apiconfig/selfcareintegration/util/TestUtil.java
  src/test/resources/application.properties
  src/test/resources/request/get_segregation_codes_ok1.json
  src/test/resources/request/get_segregation_codes_ok2.json
  src/test/resources/response/get_creditorinstitution_segregationcodes_ok1.json
  src/test/resources/response/get_creditorinstitution_segregationcodes_ok2.json
  src/test/resources/response/get_creditorinstitution_segregationcodes_ok3.json
  src/test/resources/response/get_creditorinstitution_segregationcodes_ok4.json
Labels: bug, size/large, minor

#51 fixing mapping to new model
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/config/MappingsConfiguration.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/controller/IbanController.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/mapper/ConvertIbanMasterToIbanDetailsTemp.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/model/iban/IbanEnhanced.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/model/iban/IbansEnhanced.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/service/IbansService.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/util/Constants.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/util/OffsetDateTimeDeserializer.java
Labels: bug
