Repository pagopa/pagopa-api-config-selfcare-integration, pull requests merged in 2024-06, with the labels that each got.

#55 hotfix parallel stream idDominio
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/service/CreditorInstitutionsService.java
Labels: size/small

#54 [VAS-759] Backoffice export ec stazioni upgrade
  openapi/openapi.json
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/mapper/ConvertPaStazionePaToCreditorInstitutionDetail.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/model/creditorinstitution/CreditorInstitutionDetail.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/util/Utility.java
  src/main/resources/application-local.properties
  src/test/java/it/gov/pagopa/apiconfig/selfcareintegration/service/BrokersServiceTest.java
  src/test/java/it/gov/pagopa/apiconfig/selfcareintegration/util/TestUtil.java
  src/test/resources/response/get_creditor_institution_details_ok1.json
  src/test/resources/response/get_creditor_institution_details_ok2.json
  src/test/resources/response/get_creditor_institution_details_ok3.json
Labels: size/small, patch

#56 [VAS-1113] feat: Improvement get available CI for station api
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/controller/CreditorInstitutionController.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/exception/AppError.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/mapper/ConvertPaToCreditorInstitutionInfo.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/model/creditorinstitution/CreditorInstitutionInfo.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/repository/ExtendedCreditorInstitutionStationRepository.java
  src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/service/CreditorInstitutionsService.java
  src/main/resources/h2/schema-h2.sql
  src/test/java/it/gov/pagopa/apiconfig/selfcareintegration/controller/CreditorInstitutionsControllerTest.java
  src/test/java/it/gov/pagopa/apiconfig/selfcareintegration/service/CreditorInstitutionsServiceTest.java
Labels: enhancement, size/small, minor
